#!/usr/bin/env python3
"""Render safe RTLSDR-Airband and Icecast configuration from add-on options."""

from __future__ import annotations

import html
import os
import secrets
import sys
from pathlib import Path


def truthy(value: str | None) -> bool:
    return str(value or "").strip().lower() in {"1", "true", "yes", "on"}


def quoted(value: object) -> str:
    return '"' + str(value).replace("\\", "\\\\").replace('"', '\\"') + '"'


def csv_values(name: str) -> list[str]:
    return [part.strip() for part in os.getenv(name, "").split(",") if part.strip()]


def source_password(path: Path) -> str:
    configured = os.getenv("AIRBAND_SOURCE_PASSWORD", "").strip()
    if configured:
        return configured
    try:
        existing = path.read_text(encoding="utf-8").strip()
        if existing:
            return existing
    except OSError:
        pass
    generated = secrets.token_urlsafe(24)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(generated + "\n", encoding="utf-8")
    os.chmod(path, 0o600)
    return generated


def frequencies_and_labels() -> tuple[list[str], list[str]]:
    raw_frequencies = csv_values("AIRBAND_FREQUENCIES")
    if not raw_frequencies:
        raise ValueError("AIRBAND_FREQUENCIES must contain at least one civil-airband frequency")
    frequencies: list[str] = []
    for value in raw_frequencies:
        frequency = float(value)
        if not 118.0 <= frequency <= 137.0:
            raise ValueError(f"VHF frequency {value} is outside the 118-137 MHz civil airband")
        frequencies.append(f"{frequency:.3f}")
    raw_labels = csv_values("AIRBAND_LABELS")
    labels = [raw_labels[index] if index < len(raw_labels) else f"Channel {index + 1}" for index in range(len(frequencies))]
    return frequencies, labels


def render_airband(password: str) -> str:
    frequencies, labels = frequencies_and_labels()
    squelch = float(os.getenv("AIRBAND_SQUELCH", "-28"))
    if squelch > 0:
        squelch = -squelch
    if not -100 <= squelch <= 0:
        raise ValueError("AIRBAND_SQUELCH must be between -100 and 0 dBFS")
    local_mount = os.getenv("AIRBAND_MOUNT", "baiamonte-airband.mp3").strip().lstrip("/")
    outputs = [f'''{{
          type = "icecast";
          server = "127.0.0.1";
          port = 8000;
          mountpoint = {quoted(local_mount)};
          username = "source";
          password = {quoted(password)};
          name = {quoted(os.getenv("HTML_SITE_NAME", "Tenuta Baiamonte Airband"))};
          genre = "Aviation";
          description = "Tenuta Baiamonte civil aviation receiver";
          send_scan_freq_tags = true;
        }}''']
    if truthy(os.getenv("AIRNAV_VHF_ENABLED")):
        required = ("AIRNAV_VHF_SERVER", "AIRNAV_VHF_PASSWORD", "AIRNAV_VHF_MOUNT")
        missing = [name for name in required if not os.getenv(name, "").strip()]
        if missing:
            raise ValueError("AirNav VHF sharing is enabled but values are missing: " + ", ".join(missing))
        outputs.append(f'''{{
          type = "icecast";
          server = {quoted(os.environ["AIRNAV_VHF_SERVER"].strip())};
          port = {int(os.getenv("AIRNAV_VHF_PORT", "8000"))};
          mountpoint = {quoted(os.environ["AIRNAV_VHF_MOUNT"].strip().lstrip("/"))};
          username = {quoted(os.getenv("AIRNAV_VHF_USERNAME", "source"))};
          password = {quoted(os.environ["AIRNAV_VHF_PASSWORD"])};
          name = {quoted(os.getenv("HTML_SITE_NAME", "Tenuta Baiamonte Airband"))};
          genre = "Aviation";
          description = "Tenuta Baiamonte civil aviation receiver";
          send_scan_freq_tags = true;
        }}''')
    output_block = ",\n        ".join(outputs)
    return f'''# Generated by Baiamonte ADS-B. Configure this in Home Assistant.
devices: ({{
  type = "rtlsdr";
  index = {int(os.getenv("VHF_DEVICE", "1"))};
  gain = {float(os.getenv("AIRBAND_GAIN", "28"))};
  correction = {int(os.getenv("VHF_PPM", "0"))};
  mode = "scan";
  channels: ({{
    freqs = ( {", ".join(frequencies)} );
    labels = ( {", ".join(quoted(label) for label in labels)} );
    squelch_threshold = {int(round(squelch))};
    outputs: (
        {output_block}
    );
  }});
}});
'''


def render_icecast(password: str) -> str:
    admin_password = secrets.token_urlsafe(24)
    return f'''<icecast>
  <location>Tenuta Baiamonte, Sicily</location>
  <admin>local@tenutabaiamonte.invalid</admin>
  <limits><clients>24</clients><sources>3</sources><queue-size>524288</queue-size><client-timeout>30</client-timeout><header-timeout>15</header-timeout><source-timeout>10</source-timeout></limits>
  <authentication><source-password>{html.escape(password)}</source-password><relay-password>{admin_password}</relay-password><admin-user>admin</admin-user><admin-password>{admin_password}</admin-password></authentication>
  <hostname>baiamonte-adsb.local</hostname>
  <listen-socket><port>8000</port><bind-address>127.0.0.1</bind-address></listen-socket>
  <fileserve>0</fileserve>
  <paths><basedir>/usr/share/icecast2</basedir><logdir>/var/log/icecast2</logdir><webroot>/usr/share/icecast2/web</webroot><adminroot>/usr/share/icecast2/admin</adminroot></paths>
  <logging><accesslog>access.log</accesslog><errorlog>error.log</errorlog><loglevel>2</loglevel><logsize>10000</logsize></logging>
  <security><chroot>0</chroot><changeowner><user>icecast2</user><group>icecast</group></changeowner></security>
</icecast>
'''


def main() -> int:
    airband_path = Path(sys.argv[1] if len(sys.argv) > 1 else "/etc/rtl_airband.conf")
    icecast_path = Path(sys.argv[2] if len(sys.argv) > 2 else "/etc/icecast2/icecast.xml")
    password_path = Path(os.getenv("AIRBAND_PASSWORD_FILE", "/data/airband-source-password"))
    password = source_password(password_path)
    airband_path.parent.mkdir(parents=True, exist_ok=True)
    icecast_path.parent.mkdir(parents=True, exist_ok=True)
    airband_path.write_text(render_airband(password), encoding="utf-8")
    icecast_path.write_text(render_icecast(password), encoding="utf-8")
    os.chmod(airband_path, 0o600)
    os.chmod(icecast_path, 0o600)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, TypeError, ValueError) as error:
        print(f"VHF configuration error: {error}", file=sys.stderr, flush=True)
        raise SystemExit(2)
