const $=selector=>document.querySelector(selector),$$=selector=>[...document.querySelectorAll(selector)];
const geoMap=new BaiamonteMap($('#radar-map'));
const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const fmt=(value,suffix='')=>value===null||value===undefined||value===''?'—':`${value}${suffix}`;
const age=value=>value===null||value===undefined?'just now':value<60?`${Math.round(value)}s ago`:`${Math.round(value/60)}m ago`;

function showPage(id,addHistory=false){const page=$(`#${id}`)?id:'overview';$$('.nav').forEach(node=>node.classList.toggle('active',node.dataset.page===page));$$('.page').forEach(node=>node.classList.toggle('active',node.id===page));$('#page-title').textContent={overview:'Aircraft overview',aircraft:'Live aircraft',portals:'Feeder portals'}[page]||'Aircraft overview';if(addHistory)history.pushState({page},'',`#${page}`);else history.replaceState({page},'',`#${page}`);window.scrollTo({top:0,behavior:'smooth'})}
$$('.nav').forEach(node=>node.onclick=()=>showPage(node.dataset.page,true));$$('[data-go]').forEach(node=>node.onclick=()=>showPage(node.dataset.go,true));window.addEventListener('popstate',()=>showPage(location.hash.slice(1)||'overview'));

function aircraftRow(item){return `<div class="recent-row"><div class="aircraft-icon"><svg><use href="#i-plane"/></svg></div><span><b>${esc(item.flight)}</b><small>ICAO ${esc(item.hex.toUpperCase()||'UNKNOWN')} · ${esc(fmt(item.altitude,' ft'))}</small></span><em>${esc(fmt(item.speed,' kt'))}</em></div>`}
function aircraftCard(item){return `<article class="aircraft-card"><div class="aircraft-card-top"><div class="aircraft-icon"><svg><use href="#i-plane"/></svg></div><span class="status">${item.lat!==null&&item.lon!==null?'Positioned':'Signal only'}</span></div><h3>${esc(item.flight)}</h3><span class="hex">ICAO ${esc(item.hex.toUpperCase()||'UNKNOWN')} · seen ${esc(age(item.seen))}</span><div class="aircraft-metrics"><div><small>ALTITUDE</small><b>${esc(fmt(item.altitude,' ft'))}</b></div><div><small>GROUND SPEED</small><b>${esc(fmt(item.speed,' kt'))}</b></div><div><small>TRACK</small><b>${esc(fmt(item.track,'°'))}</b></div><div><small>MESSAGES</small><b>${esc(fmt(item.messages))}</b></div></div></article>`}
function portalRow(item){const state=!item.enabled?'Disabled':item.configured?'Ready':'Needs key';return `<div class="portal-row"><i class="state-dot ${item.enabled?(item.configured?'ready':'pending'):''}"></i><b>${esc(item.name)}</b><small>${state}</small></div>`}
function portalCard(item){const state=!item.enabled?'Disabled':item.configured?'Ready to feed':'Credential required';const detail=!item.enabled?'This network is not receiving estate aircraft data.':item.configured?'The portal is enabled and its credential is present.':'Enable sharing only after adding the portal credential in app configuration.';return `<article class="portal-card"><div class="portal-card-top"><div class="route-icon"><svg><use href="#i-network"/></svg></div><span class="status ${!item.enabled?'off':item.configured?'ready':''}">${state}</span></div><h3>${esc(item.name)}</h3><small>MULTI-PORTAL FEED</small><p>${detail}</p></article>`}

function renderMap(aircraft,location){const map=$('#radar-map');$$('.aircraft-marker,.estate-map-marker').forEach(node=>node.remove());const positioned=aircraft.filter(item=>typeof item.lat==='number'&&typeof item.lon==='number');$('#map-empty').classList.toggle('hidden',positioned.length>0);const center={lat:typeof location.lat==='number'?location.lat:(positioned[0]?.lat??37.847),lon:typeof location.lon==='number'?location.lon:(positioned[0]?.lon??14.925)};const view=geoMap.render(center,positioned);const estatePoint=view.project(center.lat,center.lon);const estate=document.createElement('div');estate.className='estate-map-marker';estate.style.left=`${estatePoint.x}px`;estate.style.top=`${estatePoint.y}px`;estate.innerHTML='<span>◆</span><b>Tenuta Baiamonte</b>';map.appendChild(estate);positioned.forEach(item=>{const point=view.project(item.lat,item.lon);if(point.x<0||point.y<0||point.x>map.clientWidth||point.y>map.clientHeight)return;const node=document.createElement('div');node.className='aircraft-marker';node.style.left=`${point.x}px`;node.style.top=`${point.y}px`;node.style.setProperty('--track',`${item.track||0}deg`);node.dataset.name=item.flight;node.innerHTML='<span>▲</span>';node.title=`${item.flight} · ${fmt(item.altitude,' ft')} · ${fmt(item.speed,' kt')}`;map.appendChild(node)})}

function render(data){const aircraft=data.aircraft||[],portals=data.portals||[],ready=data.receiver.ready,active=portals.filter(item=>item.enabled),configured=active.filter(item=>item.configured);$('#side-light').classList.toggle('online',ready);$('#hero-light').classList.toggle('online',ready);$('#side-status').textContent=ready?'Receiver online':'Waiting for receiver';$('#hero-status').textContent=ready?'The Baiamonte 1090 MHz receiver is online':'Waiting for dump1090 aircraft data';$('#receiver-status').textContent=ready?'Online':data.receiver.enabled?'Starting':'Disabled';$('#aircraft-count').textContent=`${data.counts.aircraft} active`;$('#positioned-count').textContent=`${data.counts.positioned} mapped`;$('#portal-count').textContent=`${configured.length} of ${active.length} ready`;$('#nav-count').textContent=data.counts.aircraft;$('#aircraft-badge').textContent=`${data.counts.aircraft} active`;$('#last-check').textContent=`Updated ${new Date(data.generated_at*1000).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'})}`;$('#decoder-card').textContent=ready?'Receiver online':data.receiver.enabled?'Starting decoder':'Receiver disabled';$('#decoder-detail').textContent=data.receiver.source_age===null?'Waiting for aircraft.json':`Aircraft data updated ${age(data.receiver.source_age)}`;const latest=aircraft[0];$('#latest-flight').textContent=latest?.flight||'No aircraft yet';$('#latest-detail').textContent=latest?`${fmt(latest.altitude,' ft')} · ${age(latest.seen)}`:'The local sky is clear';$('#sharing-card').textContent=active.length?`${configured.length} portals ready`:'Private receiver';$('#location-label').textContent=typeof data.location.lat==='number'&&typeof data.location.lon==='number'?`${data.location.lat.toFixed(4)}, ${data.location.lon.toFixed(4)} · ${fmt(data.location.alt,' m MSL')} · ${data.location.source||'Configured location'}`:'Waiting for receiver location';renderMap(aircraft,data.location);$('#recent-aircraft').innerHTML=aircraft.length?aircraft.slice(0,5).map(aircraftRow).join(''):'<div class="empty">No aircraft broadcasts have been decoded yet.</div>';$('#aircraft-grid').innerHTML=aircraft.length?aircraft.map(aircraftCard).join(''):'<article class="panel empty">The receiver is scanning. Aircraft will appear here automatically.</article>';$('#portal-summary').innerHTML=portals.map(portalRow).join('');$('#portal-grid').innerHTML=portals.map(portalCard).join('')}

async function refresh(){const button=$('#refresh');button.disabled=true;try{const response=await fetch('api/status',{cache:'no-store'});if(!response.ok)throw new Error(`Dashboard API ${response.status}`);render(await response.json())}catch(error){$('#receiver-status').textContent='Dashboard unavailable';$('#hero-status').textContent='Waiting for the Baiamonte ADS-B service';console.error(error)}finally{button.disabled=false}}
$('#refresh').onclick=refresh;showPage(location.hash.slice(1)||'overview');refresh();setInterval(refresh,10000);
