#!/command/with-contenv bash
source /export-env-from-config.sh

if [[ "${AIRBAND_ENABLED:-false}" != "true" ]]; then
  exec tail -f /dev/null
fi

until [[ -s /etc/rtl_airband.conf ]] && nc -z 127.0.0.1 8000; do sleep 1; done
exec rtl_airband -F -e -c /etc/rtl_airband.conf
